version: '3.8'

services:
  backend:
    image: robotito_back
    container_name: back     
   
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production  # Adjust as needed
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/robotito_google_cloud_key.json 
      - MODEL_API=gemini
      - TTS=gemini
      - STT=gemini
    volumes:
      - ./back/robotito_google_cloud_key.json:/robotito_google_cloud_key.json:ro
      - ./backend:/data  # Mount the backend directory
    networks:
      - app-network

  frontend:
    image: robotito_front
    container_name: front
    volumes:      
      - ./fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local  #