version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: robotito_db
    environment:
      - POSTGRES_USER=robotito
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=robotito_db
    ports:
      - "5432:5432"
    volumes:
      - ./robotito_db:/var/lib/postgresql/data 
    restart: unless-stopped
    networks:
      - app-network
  backend:
    image: chuchip/robotito_back
    container_name: back     
   
    environment:
      - FLASK_ENV=production  # Adjust as needed
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/robotito_google_cloud_key.json 
      - MAX_LENGHT_ANSWERS=200
      - MAX_HISTORY=20
      - LOG_LEVEL=10
      - MODEL_API=gemini
      - TTS=gemini
      - STT=gemini
      - DB_HOST=db:5432
      - DB_PASSWORD=secret
      - DB_USER=robotito_db
    volumes:
      - ./robotito_google_cloud_key.json:/robotito_google_cloud_key.json:ro
      - ./robotito_db:/app/robotito_db 
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: chuchip/robotito_front
    container_name: front
    volumes:
      - ./default-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

