version: '3.8'

services:
  backend:
    image: chuchip/robotito_back
    container_name: back     
   
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production  # Adjust as needed
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/robotito_google_cloud_key.json
      - TTS=gemini # kokoro/gemini
      - STT=gemini # local/gemini
      - MODEL_API=gemini # ollama / openai / gemini
      - MAX_LENGHT_ANSWERS=250 # 0=Disable Max lenght of answers
      - MAX_HISTORY=16 # Max history is unlimiteda
      - LOG_LEVEL=10
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # E
    volumes:
      - ./back/robotito_google_cloud_key.json:/robotito_google_cloud_key.json:ro
      - ./backend-data:/app/robotito_db  # Mount the backend directory
    networks:
      - app-network

  frontend:
    image: chuchip/robotito_front
    container_name: front
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local  